spring:
  profiles:
    active: dev
  application:
    name: knowledge-backend

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics
  endpoint:
    health:
      show-details: never
