spring:
  profiles:
    active: dev
  application:
    name: knowledge-backend
  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 105MB
      file-size-threshold: 1MB

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics
  endpoint:
    health:
      show-details: never
